# Stage 1: Install dependencies and build shared components
FROM node:22-slim AS dev_dependencies
WORKDIR /usr/src/app

# Only copy workspace config and manifest files
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
# Copy all package.json files from the subdirectories
COPY packages/shared/package.json ./packages/shared/
COPY packages/website/package.json ./packages/website/
COPY packages/admin/package.json ./packages/admin/

# Install all dependencies (this layer is only invalidated by manifest changes)
RUN corepack enable
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Stage 2: Create a dev container for the `admin` app
FROM dev_dependencies AS admin_dev
WORKDIR /usr/src/app
# The `node_modules` are copied from the dev_dependencies stage
# Copy the source code for the relevant packages
COPY . ./
ENTRYPOINT ["pnpm", "--filter", "admin", "run", "dev"]


# Stage 3: Create a dev container for the `website` app
FROM dev_dependencies AS website_dev
WORKDIR /usr/src/app
# Copy the source code for the relevant packages
COPY . ./
ENTRYPOINT ["pnpm", "--filter", "website", "run", "dev"]
