# Stage 1: Install dependencies and build shared components
FROM node:22-slim AS dev_dependencies
WORKDIR /usr/src/app

# Only copy workspace config and manifest files
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
# Copy all package.json files from the subdirectories

# Install all dependencies (this layer is only invalidated by manifest changes)
RUN corepack enable
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm fetch --frozen-lockfile
# Stage 2: Create a dev container for the `admin` app
FROM dev_dependencies AS admin_dev
WORKDIR /usr/src/app
COPY . ./
# next pnpm install is to generate node_modules for the admin package only
# This is needed to create symlinks for local packages and to install peer dependencies and binaries
RUN pnpm install --filter admin --prefer-offline
ENTRYPOINT ["pnpm", "--filter", "admin", "run", "dev"]


# Stage 3: Create a dev container for the `website` app
FROM dev_dependencies AS website_dev
WORKDIR /usr/src/app
COPY . ./
# next pnpm install is to generate node_modules for the website package only
# This is needed to create symlinks for local packages and to install peer dependencies and binaries
RUN pnpm install --filter website --prefer-offline
ENTRYPOINT ["pnpm", "--filter", "website", "run", "dev"]
